---

- name: Post building phase
  hosts: localhost
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/python' if force_python2 is defined else '/usr/bin/python3' }}"
    docker_push: "{{ lookup('env', 'DOCKER_PUSH') | default(False) }}"
  tasks:

    - name: Save container to image
      when: build_vars.container.name is defined
      block:

        - name: Load pipeline variable from file
          ansible.builtin.set_fact:
            build_vars: "{{ lookup('file', 'docker-settings.yml') | from_yaml }}"

        - name: Save running container as image
          ansible.builtin.command: >-
            docker commit {{ build_vars.container.name }} {{ build_vars.image.name }}:{{ build_vars.image.tag }}
          changed_when: true
          register: _docker_commit

        - name: Add additional tags
          ansible.builtin.command: >-
            docker image tag {{ build_vars.image.name }}:{{ build_vars.image.tag }} {{ build_vars.image.name }}:{{ item }}
          changed_when: true
          loop: "{{ build_vars.image.tags | default([]) }}"
