---

- hosts: localhost
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/python' if force_python2 is defined else '/usr/bin/python3' }}"
  tasks:
    - name: Construct basic auth
      set_fact:
        docker_auth: >-
          {{ docker_login_user + ':' + docker_login_password | b64encode }}
