---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Prepare host for docker_build using external roles
  ansible.builtin.include_tasks: prepare.yml
  when: docker_build_preparation|bool

- name: Install all packages required
  ansible.builtin.package:
    name: "{{ docker_build_packages }}"
    state: present
  become: yes

- name: Install all pip packages required
  ansible.builtin.pip:
    name: "{{ docker_build_pip_packages }}"
    state: present
  become: yes
  tags: molecule-idempotence-notest

- name: Create destination directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_build_location }}"
  become: yes

- name: Get directory structure
  ansible.builtin.set_fact:
    filelist: "{{ lookup('filetree', 'files/', wantlist=True) }}"

- name: Setup directory structure
  ansible.builtin.file:
    path: "{{ docker_build_location }}/{{ item.path }}"
    state: directory
    mode: "0755"
  loop: "{{ filelist }}"
  loop_control:
     label:
       - "{{ item.path }}"
  when: item.state == 'directory'
  become: yes

- name: Copy all scripts + templates
  ansible.builtin.copy:
    src: "files/{{ item.path }}"
    dest: "{{ docker_build_location }}/{{ item.path }}"
    mode: "{{ '0755' if item.path is search('\\.sh$') else '0644' }}"
  loop: "{{ filelist }}"
  loop_control:
     label:
       - "{{ item.path }}"
  when: item.state == 'file'
  become: yes

- name: Link from /usr/local/bin
  ansible.builtin.file:
    src: "{{ docker_build_location }}/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - docker-build.sh
    - docker-init.sh
  become: yes
