---

- name: Prepare host for docker_build
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - python
    - docker
    - docker_compose
  when: ansible_distribution != 'Alpine'

- name: Install ansible
  ansible.builtin.pip:
    name: ansible
    state: present
