---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    docker_build_preparation: True
    docker_daemon_options: {'storage-driver': 'vfs'}
  tasks:
    - name: Include role 'ansible-role-docker_build'
      ansible.builtin.include_role:
        name: ansible-role-docker_build

- name: Converge post playbook
  ansible.builtin.import_playbook: converge-post.yml
  when: molecule_converge_post is undefined or molecule_converge_post | bool
