---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    docker_build_preparation: True
    docker_daemon_options: {'storage-driver': 'vfs'}
  tasks:
    - name: Include role 'ansible-role-docker_build'
      include_role:
        name: ansible-role-docker_build
